name: Python package

on:
  release:
    types: [created, published, released]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 twine
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Build wheel
      run: |
        python setup.py bdist_wheel --python-tag cp311 --plat-name win_amd64
        python setup.py bdist_wheel --python-tag cp312 --plat-name win_amd64
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: dist/*
    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*